# QCOW2 image format builder
{ config, lib, pkgs, modulesPath, ... }:
let
  # Complete standalone configuration.nix for the deployed system
  standaloneConfig = ''
    # NixOS OpenStack Configuration
    # This file was generated by nixos-openstack and can be customized.
    # https://github.com/cloudnull/nixos-openstack
    { config, lib, pkgs, modulesPath, ... }: {
      imports = [
        "''${toString modulesPath}/profiles/qemu-guest.nix"
      ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

      nix = {
        nixPath = [
          "nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos"
          "nixos-config=/etc/nixos/configuration.nix"
          "/nix/var/nix/profiles/per-user/root/channels"
        ];
        settings = {
          auto-optimise-store = true;
          experimental-features = [ "nix-command" "flakes" ];
        };
      };

      fileSystems = {
        "/boot" = {
          device = "/dev/disk/by-label/ESP";
          fsType = "vfat";
          options = [ "nofail" "x-systemd.device-timeout=5s" ];
        };
        "/" = {
          device = "/dev/disk/by-label/nixos";
          autoResize = true;
          fsType = "ext4";
        };
      };

      boot = {
        tmp.cleanOnBoot = true;
        growPartition = true;
        kernelPackages = pkgs.linuxPackages_latest;
        kernelParams = [ "console=ttyS0" ];
        loader = {
          systemd-boot.enable = true;
          efi.canTouchEfiVariables = true;
          grub.device = lib.mkDefault "/dev/vda";
        };
      };

      networking = {
        useDHCP = false;
        dhcpcd.enable = false;
        wireless.enable = false;
      };

      systemd.network.enable = true;

      system = {
        stateVersion = "25.11";
        userActivationScripts.zshrc = "touch .zshrc";
        autoUpgrade = {
          enable = true;
          allowReboot = true;
          flake = "github:cloudnull/nixos-openstack";
          flags = [
            "--update-input"
            "nixpkgs"
            "-L"
          ];
        };
      };

      users.users.nixos = {
        isNormalUser = true;
        extraGroups = [ "wheel" ];
        shell = pkgs.zsh;
      };

      programs.zsh = {
        enable = true;
        enableCompletion = true;
        autosuggestions.enable = true;
        syntaxHighlighting.enable = true;
        shellAliases = {
          ll = "ls -l";
          nixos-rebuild-flake = "sudo nixos-rebuild switch --flake github:cloudnull/nixos-openstack";
        };
      };

      environment = {
        systemPackages = with pkgs; [
          htop
          tmux
          vim-full
          zsh
        ];
        variables.EDITOR = "vim";
      };

      security.sudo.wheelNeedsPassword = false;

      services = {
        resolved = {
          enable = true;
          dnssec = "false";
        };
        openssh.enable = true;
        qemuGuest.enable = true;
        cloud-init = {
          enable = true;
          network.enable = true;
        };
      };
    }
  '';
in {
  system.build.qcow2 = import "${toString modulesPath}/../lib/make-disk-image.nix" {
    inherit lib config pkgs;
    name = "nixos";
    format = "qcow2-compressed";
    partitionTableType = "efi";
    copyChannel = true;
    configFile = pkgs.writeText "configuration.nix" standaloneConfig;
  };
}
